### ISSUE TITLE
Уменьшение скорости после перехода на Scala

### ISSUE THREAD

**Issue by levkopo** [KayJamLang/core#18]
Версия на Java раньше могла протестировать все тесты за 14-20 секунд.
![image](https://user-images.githubusercontent.com/40952805/126317949-9bd036d1-6659-48c7-a843-f896aafbf964.png)

После перехода тесты начали выполняться в два раза медленнее
![image](https://user-images.githubusercontent.com/40952805/126318071-bd8ccadd-385e-4e5d-8965-366a0e9004ce.png)

#17

**Comment by Domaman202** [comment]
лол

**Comment by levkopo** [comment]
Теперь проект на Java
