### ISSUE TITLE
ААААААААААААААААААААААААААААААААААА

### ISSUE THREAD

**Issue by Domaman202** [KayJamLang/core#20]
его (@levkopo) COMMIT-ЫЫЫЫЫЫ иногда пугают меня
![Без имени](https://user-images.githubusercontent.com/51743763/130361616-9a0a2b49-2035-43fb-a337-23034ab217d6.png)

**Comment by levkopo** [comment]
Щас подзатыльник дам за ложные issues

**Comment by Domaman202** [comment]
они не ложные
они правдивые
